language: php

php:
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION=3.4.x CMF_VERSION=^2.0
  - SYMFONY_VERSION=4.0.x CMF_VERSION=dev-master
  - SYMFONY_VERSION=dev-master CMF_VERSION=dev-master

before_script:
  - composer require "symfony/config:${SYMFONY_VERSION}" "symfony/http-foundation:${SYMFONY_VERSION}" "symfony/routing:${SYMFONY_VERSION}" "symfony/yaml:${SYMFONY_VERSION}" "symfony-cmf/routing:${CMF_VERSION}"

script:
  - ./vendor/bin/phpunit --coverage-text

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=4.0.x CMF_VERSION=dev-master
    - env: SYMFONY_VERSION=dev-master CMF_VERSION=dev-master
