language: php

php:
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION=3.4.x
  - SYMFONY_VERSION=3.4.x-dev
  - SYMFONY_VERSION=4.0.x
  - SYMFONY_VERSION=4.0.x-dev
  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION}

script:
  - ./vendor/bin/phpunit --coverage-text

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=3.4.x-dev
    - env: SYMFONY_VERSION=4.0.x-dev
    - env: SYMFONY_VERSION=dev-master
